language: python
install:
  - pip install tox
script:
  - tox
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=flake8

