language: python
install:
  - pip install tox
script:
  - tox
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.7
      - python3.4
      - python3.5
      - python3.6
env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py34-django111
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=py35-django111
  - TOXENV=py36-django18
  - TOXENV=py36-django19
  - TOXENV=py36-django110
  - TOXENV=py36-django111
  - TOXENV=flake8

