language: python
install:
  - pip install tox
script:
  - tox
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.7
      - python3.4
      - python3.4-dev
      - python3.5
      - python3.5-dev
      - python3.6
      - python3.6-dev
env:
  - TOXENV=py27-django111-wagtail111
  - TOXENV=py27-django111-wagtail112
  - TOXENV=py27-django111-wagtail113
  - TOXENV=py34-django111-wagtail111
  - TOXENV=py34-django111-wagtail112
  - TOXENV=py34-django111-wagtail113
  - TOXENV=py35-django111-wagtail111
  - TOXENV=py35-django111-wagtail112
  - TOXENV=py35-django111-wagtail113
  - TOXENV=py36-django111-wagtail111
  - TOXENV=py36-django111-wagtail112
  - TOXENV=py36-django111-wagtail113
  - TOXENV=flake8
